import React, { useState, useEffect, useRef } from 'react';
import { Mic, MicOff, AlertCircle } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { useChat } from '../context/ChatContext';
import { motion } from 'motion/react';

// Wrap PCM data generated by the microphone to send it to the server
function float32ToPcm(float32Array: Float32Array): string {
  const pcm16 = new Int16Array(float32Array.length);
  for (let i = 0; i < float32Array.length; i++) {
    const s = Math.max(-1, Math.min(1, float32Array[i]));
    pcm16[i] = s < 0 ? s * 0x8000 : s * 0x7FFF;
  }
  const buffer = new ArrayBuffer(pcm16.length * 2);
  const view = new DataView(buffer);
  for (let i = 0; i < pcm16.length; i++) {
    view.setInt16(i * 2, pcm16[i], true); // true for little-endian
  }
  let binary = '';
  const bytes = new Uint8Array(buffer);
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

const LiveScreen: React.FC = () => {
  const { geminiApiKey, aiProfile } = useApp();
  const { chatHistory, addChatMessage } = useChat();
  const [isConnected, setIsConnected] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const wsRef = useRef<WebSocket | null>(null);
  const audioCtxRef = useRef<AudioContext | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const processorRef = useRef<ScriptProcessorNode | null>(null);

  const audioQueueRef = useRef<AudioBuffer[]>([]);
  const isPlayingRef = useRef(false);
  const nextStartTimeRef = useRef(0);
  const liveTranscriptRef = useRef('');  // Gemini's words
  const userTranscriptRef = useRef('');   // User's spoken words

  useEffect(() => {
    return () => {
      stopRecording();
      if (wsRef.current) wsRef.current.close();
      if (audioCtxRef.current) audioCtxRef.current.close();
    };
  }, []);

  const playNextChunk = async () => {
    const queue = audioQueueRef.current;
    if (queue.length === 0 || !audioCtxRef.current) {
      isPlayingRef.current = false;
      return;
    }
    isPlayingRef.current = true;
    const ctx = audioCtxRef.current;
    const buffer = queue.shift()!;
    const source = ctx.createBufferSource();
    source.buffer = buffer;
    source.connect(ctx.destination);

    const currentTime = ctx.currentTime;
    // ensure gapless or minimal gap play
    if (nextStartTimeRef.current < currentTime) {
      nextStartTimeRef.current = currentTime + 0.05; 
    }
    source.start(nextStartTimeRef.current);
    nextStartTimeRef.current += buffer.duration;
    
    source.onended = () => {
      playNextChunk();
    };
  };

  const handleAudioChunk = async (base64Audio: string) => {
    if (!audioCtxRef.current) return;
    const binary = atob(base64Audio);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    
    const pcm16 = new Int16Array(bytes.buffer);
    const float32 = new Float32Array(pcm16.length);
    for (let i = 0; i < pcm16.length; i++) {
      float32[i] = pcm16[i] / (pcm16[i] < 0 ? 0x8000 : 0x7FFF);
    }
    const audioBuffer = audioCtxRef.current.createBuffer(1, float32.length, 24000); 
    audioBuffer.getChannelData(0).set(float32);

    audioQueueRef.current.push(audioBuffer);
    if (!isPlayingRef.current) {
      playNextChunk();
    }
  };

  const startSession = async () => {
    if (!geminiApiKey) {
      setError('Gemini API key is required. Please set it in Settings.');
      return;
    }
    setError(null);
    liveTranscriptRef.current = '';
    try {
      // Create AudioContext early so incoming audio chunks are never dropped
      const AudioContext = window.AudioContext || (window as any).webkitAudioContext;
      const ctx = new AudioContext({ sampleRate: 24000 });
      audioCtxRef.current = ctx;
      nextStartTimeRef.current = 0;

      const proto = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
      const wsUrl = `${proto}//${window.location.host}/api/live`;
      const ws = new WebSocket(wsUrl);
      wsRef.current = ws;

      ws.onopen = () => {
        const historyText = chatHistory.length > 0 
          ? `\n\nPrevious conversation:\n${chatHistory.map(m => m.role + ': ' + m.content).join('\n')}`
          : '';
        const styleNote = aiProfile.geminiTtsStyle ? ` Speaking style: ${aiProfile.geminiTtsStyle}.` : '';
        const instruction = `You are ${aiProfile.name}. You must stay in character. Personality: ${aiProfile.personality}. Appearance: ${aiProfile.appearance}.${styleNote}${historyText}`;
        
        ws.send(JSON.stringify({
          setup: true,
          key: geminiApiKey,
          voice: aiProfile.geminiTtsVoice || 'Aoede',
          systemInstruction: instruction
        }));
      };

      ws.onmessage = (event) => {
        try {
          const msg = JSON.parse(event.data);
          
          if (msg.connected) {
            setIsConnected(true);
            startRecording();
          }
          if (msg.error) setError(msg.error);
          if (msg.audio) handleAudioChunk(msg.audio);
          if (msg.text && msg.role === 'model') {
            liveTranscriptRef.current += msg.text;
          }
          if (msg.text && msg.role === 'user') {
            userTranscriptRef.current += msg.text;
          }
          if (msg.interrupted) {
             // Stop current playback immediately and reset the audio pipeline
             if (audioCtxRef.current) {
               audioCtxRef.current.close();
               const AudioContext = window.AudioContext || (window as any).webkitAudioContext;
               audioCtxRef.current = new AudioContext({ sampleRate: 24000 });
             }
             audioQueueRef.current = [];
             isPlayingRef.current = false;
             nextStartTimeRef.current = 0;
             if (userTranscriptRef.current.trim()) {
               addChatMessage({ id: Date.now().toString(), role: 'user', content: userTranscriptRef.current.trim(), timestamp: Date.now() });
               userTranscriptRef.current = '';
             }
             if (liveTranscriptRef.current.trim()) {
               addChatMessage({ id: Date.now().toString(), role: 'model', content: liveTranscriptRef.current.trim(), timestamp: Date.now() });
               liveTranscriptRef.current = '';
             }
          }
        } catch (e) {
          console.error("Failed to parse message", e);
        }
      };

      ws.onclose = () => {
        setIsConnected(false);
        stopRecording();
        if (userTranscriptRef.current.trim()) {
          addChatMessage({ id: Date.now().toString(), role: 'user', content: userTranscriptRef.current.trim(), timestamp: Date.now() });
          userTranscriptRef.current = '';
        }
        if (liveTranscriptRef.current.trim()) {
          addChatMessage({ id: Date.now().toString(), role: 'model', content: liveTranscriptRef.current.trim(), timestamp: Date.now() });
          liveTranscriptRef.current = '';
        }
      };
    } catch (e: any) {
      setError(e.message || 'Failed to start Gemini Live');
    }
  };

  const startRecording = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      streamRef.current = stream;

      const ctx = audioCtxRef.current!;
      const source = ctx.createMediaStreamSource(stream);
      const processor = ctx.createScriptProcessor(4096, 1, 1);
      processorRef.current = processor;

      source.connect(processor);
      processor.connect(ctx.destination);

      processor.onaudioprocess = (e) => {
        if (!wsRef.current || wsRef.current.readyState !== WebSocket.OPEN) return;
        const inputData = e.inputBuffer.getChannelData(0);
        const base64 = float32ToPcm(inputData);
        wsRef.current.send(JSON.stringify({ audio: base64 }));
      };

      setIsRecording(true);
    } catch (e: any) {
      setError('Mic access denied or error: ' + e.message);
    }
  };

  const stopRecording = () => {
    if (processorRef.current) {
      processorRef.current.disconnect();
      processorRef.current = null;
    }
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(t => t.stop());
      streamRef.current = null;
    }
    setIsRecording(false);
  };

  const disconnectSession = () => {
    if (wsRef.current) {
      wsRef.current.close();
    }
  };

  return (
    <div className="flex flex-col h-full bg-slate-50 dark:bg-slate-900 overflow-hidden relative items-center justify-center">
      <div className="text-center w-full max-w-md p-6">
        <h2 className="text-2xl font-bold mb-2 text-indigo-900 dark:text-indigo-100">Gemini Live Voice</h2>
        <p className="text-sm text-slate-600 dark:text-slate-400 mb-8">
          Have an open-ended voice conversation. (Make sure you gave mic permissions).
        </p>

        {error && (
          <div className="mb-6 bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-100 p-3 rounded flex items-center gap-2">
            <AlertCircle size={20} />
            <span className="text-sm">{error}</span>
          </div>
        )}

        {isConnected ? (
          <div className="flex flex-col items-center justify-center gap-8">
             <motion.div 
               animate={{ scale: [1, 1.2, 1] }} 
               transition={{ repeat: Infinity, duration: 1.5 }}
               className="w-32 h-32 rounded-full bg-indigo-500 flex items-center justify-center shadow-lg shadow-indigo-500/50"
             >
                <div className="w-24 h-24 rounded-full bg-indigo-400 flex items-center justify-center">
                  <Mic className="w-12 h-12 text-white" />
                </div>
             </motion.div>
             <p className="text-indigo-700 dark:text-indigo-300 font-medium">Connected</p>
             <button 
               onClick={disconnectSession}
               className="px-6 py-3 bg-red-500 hover:bg-red-600 text-white rounded-full font-bold shadow transition-colors"
             >
               End Conversation
             </button>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center gap-8">
             <div className="w-32 h-32 rounded-full bg-slate-200 dark:bg-slate-800 flex items-center justify-center text-slate-400 dark:text-slate-600">
               <MicOff className="w-12 h-12" />
             </div>
             <button 
               onClick={startSession}
               className="px-8 py-4 bg-indigo-600 hover:bg-indigo-700 text-white rounded-full font-bold text-lg shadow-xl shadow-indigo-200 dark:shadow-indigo-900 transition-all active:scale-95"
             >
               Connect to Gemini Live
             </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default LiveScreen;
